/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package appraisal_tracker;

import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author kbiiita
 */
public class job_profile extends javax.swing.JFrame {

    /**
     * Creates new form job_profile
     */
    public job_profile() throws SQLException {
        initComponents();
        
        jLabel1.setText("EMPLOYEE  "+global.number);
        database db=new database();
        Statement stmt = null;
        try {
            stmt = (Statement) db.con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(update_profile.class.getName()).log(Level.SEVERE, null, ex);
        }
        ResultSet rs = stmt.executeQuery("SELECT department,skills,quality,consistency,reliability,initiative,ontime,workunder,guidance,adaptability,attitude,image,cooperation,communication from rating2 where username='"+global.number+"'");
        while(rs.next())
            { 
        text1.setText(rs.getString("department"));
           text2.setText(rs.getString("skills"));
             text3.setText(rs.getString("quality"));
               text4.setText(rs.getString("consistency"));
                 text5.setText(rs.getString("reliability"));
                   text6.setText(rs.getString("initiative"));
                     text7.setText(rs.getString("ontime"));
                       text8.setText(rs.getString("workunder"));
                         text9.setText(rs.getString("guidance"));
                           text10.setText(rs.getString("adaptability"));
                             text11.setText(rs.getString("attitude"));
                               text12.setText(rs.getString("image"));
                                 text13.setText(rs.getString("cooperation"));
                                   text14.setText(rs.getString("communication"));
            }
        stmt=null;
        try {
            stmt = (Statement) db.con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(update_profile.class.getName()).log(Level.SEVERE, null, ex);
        }
         rs = stmt.executeQuery("SELECT username,department,skills,quality,consistency,reliability,initiative,ontime,workunder,guidance,adaptability,attitude,image,cooperation,communication from rating where username='"+global.number+"'");
          while(rs.next())
            {
         text2p.setText(rs.getString("skills"));
             text3p.setText(rs.getString("quality"));
               text4p.setText(rs.getString("consistency"));
                 text5p.setText(rs.getString("reliability"));
                   text6p.setText(rs.getString("initiative"));
                     text7p.setText(rs.getString("ontime"));
                       text8p.setText(rs.getString("workunder"));
                         text9p.setText(rs.getString("guidance"));
                           text10p.setText(rs.getString("adaptability"));
                             text11p.setText(rs.getString("attitude"));
                               text12p.setText(rs.getString("image"));
                                 text13p.setText(rs.getString("cooperation"));
                                   text14p.setText(rs.getString("communication"));
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text13 = new javax.swing.JTextField();
        text12 = new javax.swing.JTextField();
        USERNAME10 = new javax.swing.JLabel();
        text11 = new javax.swing.JTextField();
        USERNAME9 = new javax.swing.JLabel();
        USERNAME8 = new javax.swing.JLabel();
        USERNAME7 = new javax.swing.JLabel();
        USERNAME6 = new javax.swing.JLabel();
        USERNAME5 = new javax.swing.JLabel();
        text5 = new javax.swing.JTextField();
        USERNAME3 = new javax.swing.JLabel();
        text6 = new javax.swing.JTextField();
        USERNAME4 = new javax.swing.JLabel();
        USERNAME1 = new javax.swing.JLabel();
        USERNAME2 = new javax.swing.JLabel();
        text9 = new javax.swing.JTextField();
        text10 = new javax.swing.JTextField();
        text7 = new javax.swing.JTextField();
        text8 = new javax.swing.JTextField();
        text4 = new javax.swing.JTextField();
        text1 = new javax.swing.JTextField();
        USERNAME15 = new javax.swing.JLabel();
        text3 = new javax.swing.JTextField();
        text2 = new javax.swing.JTextField();
        USERNAME12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        USERNAME11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        back1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        text14 = new javax.swing.JTextField();
        USERNAME14 = new javax.swing.JLabel();
        text2p = new javax.swing.JTextField();
        text3p = new javax.swing.JTextField();
        text5p = new javax.swing.JTextField();
        text4p = new javax.swing.JTextField();
        text7p = new javax.swing.JTextField();
        text6p = new javax.swing.JTextField();
        text8p = new javax.swing.JTextField();
        text9p = new javax.swing.JTextField();
        text10p = new javax.swing.JTextField();
        text11p = new javax.swing.JTextField();
        text12p = new javax.swing.JTextField();
        text13p = new javax.swing.JTextField();
        text14p = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        text13.setText("0");

        text12.setText("0");

        USERNAME10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        USERNAME10.setText("Organization’s image");

        text11.setText("0");

        USERNAME9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        USERNAME9.setText("Adaptability");

        USERNAME8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        USERNAME8.setText("Initiative");

        USERNAME7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        USERNAME7.setText("On time tasks’ completion");

        USERNAME6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        USERNAME6.setText("Receptivity to guidance");

        USERNAME5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        USERNAME5.setText("Work under pressure");

        text5.setText("0");

        USERNAME3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        USERNAME3.setText("Reliability");

        text6.setText("0");

        USERNAME4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        USERNAME4.setText("Consistency");

        USERNAME1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        USERNAME1.setText("Skills");

        USERNAME2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        USERNAME2.setText("Quality of work output");
        USERNAME2.setToolTipText("");

        text9.setText("0");

        text10.setText("0");

        text7.setText("0");

        text8.setText("0");

        text4.setText("0");

        USERNAME15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        USERNAME15.setText("DEPARTMENT");

        text3.setText("0");

        text2.setText("0");

        USERNAME12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        USERNAME12.setText("Attitude");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("(OUT of )");

        USERNAME11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        USERNAME11.setText("Cooperation");

        back1.setText("BACK");
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });

        jButton7.setText("LOGOUT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        text14.setText("0");

        USERNAME14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        USERNAME14.setText("Communication ");

        text2p.setText("0");
        text2p.setToolTipText("");
        text2p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text2pActionPerformed(evt);
            }
        });

        text3p.setText("0");

        text5p.setText("0");

        text4p.setText("0");

        text7p.setText("0");

        text6p.setText("0");

        text8p.setText("0");

        text9p.setText("0");

        text10p.setText("0");

        text11p.setText("0");

        text12p.setText("0");

        text13p.setText("0");

        text14p.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(USERNAME15, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114)
                                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(USERNAME3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(USERNAME4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(USERNAME8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(USERNAME9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(USERNAME11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(USERNAME1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(USERNAME10, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(USERNAME6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(USERNAME5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(USERNAME7, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(USERNAME12, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(USERNAME14, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(USERNAME2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(text13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(text12, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text11, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text2)
                                    .addComponent(text14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(text4p)
                                    .addComponent(text5p)
                                    .addComponent(text6p)
                                    .addComponent(text7p)
                                    .addComponent(text8p)
                                    .addComponent(text9p)
                                    .addComponent(text10p)
                                    .addComponent(text11p)
                                    .addComponent(text12p)
                                    .addComponent(text13p)
                                    .addComponent(text14p)
                                    .addComponent(text3p)
                                    .addComponent(text2p))
                                .addGap(44, 44, 44)))
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(USERNAME15)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(USERNAME1)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text2p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(USERNAME2)
                    .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text3p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(USERNAME4)
                                .addGap(18, 18, 18)
                                .addComponent(USERNAME3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(text5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(USERNAME8)
                            .addComponent(text6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(USERNAME7)
                            .addComponent(text7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text7p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(USERNAME5)
                            .addComponent(text8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text8p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(USERNAME6)
                            .addComponent(text9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text9p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(USERNAME9)
                            .addComponent(text10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text10p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(USERNAME12)
                            .addComponent(text11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text11p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(USERNAME10)
                            .addComponent(text12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text12p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text4p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(text5p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(text6p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(USERNAME11)
                            .addComponent(text13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(USERNAME14))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(text14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text13p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(text14p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        // TODO add your handling code here:

        job_profile.this.setVisible(false);
        logged_in_employee n = new logged_in_employee(global.number);
        n.show();

    }//GEN-LAST:event_back1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        job_profile.this.setVisible(false);
        login ln = new login();
        ln.show();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void text2pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text2pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text2pActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel USERNAME1;
    private javax.swing.JLabel USERNAME10;
    private javax.swing.JLabel USERNAME11;
    private javax.swing.JLabel USERNAME12;
    private javax.swing.JLabel USERNAME14;
    private javax.swing.JLabel USERNAME15;
    private javax.swing.JLabel USERNAME2;
    private javax.swing.JLabel USERNAME3;
    private javax.swing.JLabel USERNAME4;
    private javax.swing.JLabel USERNAME5;
    private javax.swing.JLabel USERNAME6;
    private javax.swing.JLabel USERNAME7;
    private javax.swing.JLabel USERNAME8;
    private javax.swing.JLabel USERNAME9;
    private javax.swing.JButton back1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text10;
    private javax.swing.JTextField text10p;
    private javax.swing.JTextField text11;
    private javax.swing.JTextField text11p;
    private javax.swing.JTextField text12;
    private javax.swing.JTextField text12p;
    private javax.swing.JTextField text13;
    private javax.swing.JTextField text13p;
    private javax.swing.JTextField text14;
    private javax.swing.JTextField text14p;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField text2p;
    private javax.swing.JTextField text3;
    private javax.swing.JTextField text3p;
    private javax.swing.JTextField text4;
    private javax.swing.JTextField text4p;
    private javax.swing.JTextField text5;
    private javax.swing.JTextField text5p;
    private javax.swing.JTextField text6;
    private javax.swing.JTextField text6p;
    private javax.swing.JTextField text7;
    private javax.swing.JTextField text7p;
    private javax.swing.JTextField text8;
    private javax.swing.JTextField text8p;
    private javax.swing.JTextField text9;
    private javax.swing.JTextField text9p;
    // End of variables declaration//GEN-END:variables
}
