//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Analyser.java
//  @ Date : 3/24/2012
//  @ Author : 
//
//




public class Analyser {
	public Object ItemSet;
	public Object Min confi and Support;
	public void Calculate Frequent ItemSet() {
	
	}
}
