//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Apriori.java
//  @ Date : 3/24/2012
//  @ Author : 
//
//




public class Apriori {
	public Object Basket(file);
	public void Calculate() {
	
	}
}
