//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Basket(file).java
//  @ Date : 3/24/2012
//  @ Author : 
//
//




public class Basket(file) {
	public Object Min conf.;
	public Object Min Support;
}
