//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : File.java
//  @ Date : 3/24/2012
//  @ Author : 
//
//




public class File {
	public Object Item set;
	public Object Min confidence;
	public Object Min support;
}
