//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GUI.java
//  @ Date : 3/24/2012
//  @ Author : 
//
//




public class GUI {
	public Object Buttons;
	public Object Text Fields;
	public void Input() {
	
	}
}
