//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Itemset.java
//  @ Date : 3/24/2012
//  @ Author : 
//
//




public class Itemset {
	public Object Item name;
	public Object Min conf.;
	public Object Min supp.;
}
