//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Item Set.java
//  @ Date : 3/24/2012
//  @ Author : 
//
//




public class Item Set {
	public Object Item name;
}
