//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Kim, Hyunsoo.java
//  @ Date : 3/24/2012
//  @ Author : 
//
//




public class Kim, Hyunsoo {
}
