//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Store.java
//  @ Date : 3/24/2012
//  @ Author : 
//
//




public class Store {
	public Object Itemset;
	public Object Confidence;
	public Object Support;
	public void Display Steps() {
	
	}
	
	public void Display Result() {
	
	}
}
