//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : User.java
//  @ Date : 3/24/2012
//  @ Author : 
//
//




public class User {
	public Object NAME;
	public Object ID;
	public void Input() {
	
	}
}
